### ISSUE TITLE
Support for Two Factor Auth

### ISSUE THREAD

**Issue by themizarkshow** [ineffyble/tooter#10]
To sign in, I had to turn off the 2-Factor Auth for my account. Would be nice if there was a way to support that without needing to do that.

**Comment by ineffyble** [comment]
That would be because we're using the basic authentication mechanism, rather than the proper OAuth workflow. I might need to set up some middleware to support proper OAuth, hmm.

**Comment by ineffyble** [comment]
Fixed by 8bc58cc3df3e124419505b39c710eca57588ad8d

Want to clean up addon a bit, but will release new version soon

**Comment by ineffyble** [comment]
Fixed in version 0.23, now on the Chrome store.
