### ISSUE TITLE
does it work in chromium ?

### ISSUE THREAD

**Issue by arnauldb** [ineffyble/tooter#11]
Hello,

I installed your extension, I'm logged in, but no button appears. Am I missing something ? On wich websites should the buttons appear ?

Thank you,

**Comment by remove32** [comment]
Currently it seems only twitter intents are supported. This means any time that you go to a website that can share a link or make a post to your twitter on behalf of you and click the share on twitter button, you can toot it also. Try it at youtube for example. Click the "Share" button and then click on twitter.

**Comment by arnauldb** [comment]
@remove32 thank you, I understand now. It worked, just shared a video via youtube.
