### ISSUE TITLE
mastodon.social

### ISSUE THREAD

**Issue by A350** [ineffyble/tooter#15]
no is working with mastodon.social

but, with other instances yes

whats is the problem?

thanks

**Comment by ineffyble** [comment]
Hey,

Not sure why that would be - I'm using Tooter with Mastodon.Social

What error are you running into?

**Comment by A350** [comment]
ey.. thx

this error but with chromium,  now im with chrome and working

An error occurred: TypeError: Failed to fetch

**Comment by ineffyble** [comment]
Interesting - I'll have to test in Chromium when I can. What version?

**Comment by A350** [comment]
Versión 57.0.2987.98 Built on 8.7, running on Debian 8.7 (64-bit)

**Comment by ineffyble** [comment]
Can you confirm if this is still an issue in the most recent version?

**Comment by A350** [comment]
confirm , working fine !!!
