### ISSUE TITLE
Cited tweets from tweetdeck not included on mastodon

### ISSUE THREAD

**Issue by NicolasDumoulin** [ineffyble/tooter#18]
I've tried to post a message with a citation from tweetdeck, and if the citation appears on twitter:
https://twitter.com/n_dumoulin/status/862667300012511232
It doesn't on mastodon:
https://framapiaf.org/@NicolasDumoulin/546541

**Comment by ineffyble** [comment]
Tooter 0.28 (rolling out to Chrome now, and Firefox after review) adds a citation/link to the quoted tweet, to the toot text.
