### ISSUE TITLE
Tweetdeck support broken

### ISSUE THREAD

**Issue by Natanji** [ineffyble/tooter#23]
I've just installed the extension and it works perfectly in the Twitter intent dialogue - but in Tweetdeck, there is no Toot button added to the New Tweet dialogue. Since this is claimed to be a feature, it would be nice if you could fix this, perhaps the CSS of Tweetdeck changed since?

**Comment by ineffyble** [comment]
The buttons are showing for me currently. Could you let me know of your OS, browser, and browser version, so I can try and reproduce the bug?

If you know how to look in the JavaScript console for errors, that would also be very useful.

**Comment by ineffyble** [comment]
Example of the extra buttons showing for me in Tweetdeck:
![image](https://user-images.githubusercontent.com/834880/30773091-d2a6b91e-a0ac-11e7-9897-a3f87da4198b.png)

**Comment by Natanji** [comment]
Firefox 55.0.3 (64-Bit) on Windows 10 (Creator's Update). For me it looks like this. Javascript console output is attached as screenshot as well.

<img width="175" alt="notoot" src="https://user-images.githubusercontent.com/887286/30773160-28a653f2-a06b-11e7-95d5-c7d4807204bc.PNG">
<img width="662" alt="errors" src="https://user-images.githubusercontent.com/887286/30773163-2f4ea498-a06b-11e7-9cbf-be0dafe5c002.PNG">

**Comment by ineffyble** [comment]
Huh, interesting. Looks like a Firefox specific quirk. Thank you for the screenshots, they were very helpful (I was able to replicate the problem, but not the error message in your console that was behind it).

Tooter 0.29 fixes this bug, and is currently waiting in the Mozilla review queue. Will hopefully be live soon.
