### ISSUE TITLE
Delisted from Firefox Addons store

### ISSUE THREAD

**Issue by ineffyble** [ineffyble/tooter#24]
Tooter's listing has been disabled due to lack of privacy policy:

`Please add a privacy policy to this add-on that details which user data is being sent and to what services. If your add-on makes it apparent to websites that it is installed, this must also be mentioned. The policy should be about the extension only, not a copy of the website's privacy policy. It should also be the actual text, as opposed to a link to a privacy policy on a website.
`

**Comment by icheyne** [comment]
OMG what a PITA. Is there a workaround in the meantime? Love this addon. :-)

**Comment by ineffyble** [comment]
Ugh, it turns out they never responded when I replied to their delisting.

**Comment by ineffyble** [comment]
Addon is approved now

**Comment by icheyne** [comment]
Thanks so much! Works perfectly.
